import Head from "next/head";
import Image from "next/image";
import { Roboto } from "next/font/google";
import styles from "@/styles/Home.module.css";
import bg from "../../public/waves.svg";

const roboto = Roboto({
  weight: ["400", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Bitfold</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <style>{`
          html {
            font-family: ${roboto.style.fontFamily};
          }
          a, button {
            cursor:pointer;
          }
        `}</style>
      </Head>
      <main className={styles.main}>
        <header className={styles.header}>
          <a>
            <Image priority src="Logo.svg" height={40} width={122} />
          </a>
          <nav className={styles.nav}>
            <ul className={styles.navBar}>
              <li>
                <a href="#">Features</a>
              </li>
              <li>
                <a href="#">Pricing</a>
              </li>
              <li>
                <a href="#">Market Cap</a>
              </li>
              <li>
                <a href="#">Ticker</a>
              </li>
              <li>
                <button>Download</button>
              </li>
            </ul>
          </nav>
        </header>
        <content className={styles.content}>
          <div className={styles.texts}>
            <h1>
              Trading crypto <br /> never felt so good
            </h1>
            <p>
              Bitfold allows you to trade crypto
              <br />
              currency without all the confusion.
            </p>
            <div className={styles.buttons}>
              <button>Download</button>
              <button>Learn More</button>
            </div>
          </div>
          <div className={styles.images}>
            <Image priority src="iphone.svg" height={600} width={300} />
            <Image priority src="image-cash.svg" height={200} width={300} />
          </div>
        </content>
      </main>
    </>
  );
}
